# Run every 2 hours on the hour between 10:00 - 22:00, Monday - Friday
#schedules:
#  - cron: 0 10-22/2 * * mon-fri
#    always: true
#    branches:
#      include:
#        - main

trigger: none

pool:
  vmImage: ubuntu-latest

steps:

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'AZ-Service-connection'
      scriptType: 'pscore'
      scriptLocation: 'scriptPath'
      scriptPath: '$(System.DefaultWorkingDirectory)/Update-ServiceConnections.ps1'
      # arguments: '-org "iveylabs" -project "DemoProject" -scRunning "Renewal SPN" -scTarget "SPN 2"'
      arguments: '-org "workshopsdev" -project "Devops-demos" -scRunning "AZ-Service-connection"' # Just give the name of the service connection you've used in the azureSubscription input.
      addSpnToEnvironment: true
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)